apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: app
